"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type Section = "overview" | "users" | "moderation" | "disputes" | "audit" | "controls";
type Page<T> = { items: T[]; page: number; total: number; totalPages: number };
const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000";
const token = () => typeof window === "undefined" ? "" : localStorage.getItem("accessToken") ?? "";
async function request<T>(path: string, init?: RequestInit): Promise<T> { const res = await fetch(`${API}/api/admin${path}`, { ...init, headers: { Authorization: `Bearer ${token()}`, "Content-Type": "application/json", ...(init?.headers ?? {}) } }); if (res.status === 401 || res.status === 403) throw new Error("FORBIDDEN"); if (!res.ok) throw new Error(await res.text()); return (await res.json()).data; }

const nav: [Section, string][] = [["overview", "Overview"], ["users", "Users"], ["moderation", "Moderation"], ["disputes", "Disputes"], ["audit", "Audit log"], ["controls", "Platform controls"]];
function Status({ value }: { value: string }) { return <span className={`status ${value}`}>{value.replace("_", " ")}</span>; }
function Confirm({ title, onConfirm, onCancel }: { title: string; onConfirm: (reason: string) => void; onCancel: () => void }) { const [reason, setReason] = useState(""); return <div className="backdrop"><div className="dialog" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><h2 id="confirm-title">{title}</h2><label>Reason (optional)<textarea value={reason} onChange={(e) => setReason(e.target.value)} /></label><div className="dialog-actions"><button onClick={onCancel}>Cancel</button><button className="primary" onClick={() => onConfirm(reason)}>Confirm</button></div></div></div>; }

export default function AdminPanelPage() {
  const router = useRouter(); const [section, setSection] = useState<Section>("overview"); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [confirm, setConfirm] = useState<null | { title: string; run: (reason: string) => Promise<void> }>(null);
  useEffect(() => { request<{ role: string }>("/me").then((u) => { if (u.role !== "admin") router.replace("/403"); }).catch((e) => e.message === "FORBIDDEN" ? router.replace("/403") : setError(e.message)).finally(() => setLoading(false)); }, [router]);
  const refresh = useCallback(() => { setLoading(true); setError(""); window.dispatchEvent(new Event("admin-refresh")); setTimeout(() => setLoading(false), 0); }, []);
  if (loading) return <main className="admin-shell"><p className="state">Checking administrator access…</p></main>;
  if (error) return <main className="admin-shell"><p className="state error">Unable to load admin panel: {error}</p></main>;
  return <main className="admin-shell"><aside className="admin-nav"><strong>Freelance<span>Flow</span></strong><p>ADMIN CONSOLE</p>{nav.map(([id, label]) => <button key={id} className={section === id ? "selected" : ""} onClick={() => setSection(id)}>{label}</button>)}</aside><section className="admin-content"><header className="admin-header"><div><small>Operations / Admin</small><h1>{nav.find(([id]) => id === section)?.[1]}</h1></div><button onClick={refresh} aria-label="Refresh dashboard data">↻ Refresh</button></header><Panel section={section} confirm={setConfirm} /><div aria-live="polite">{confirm && <Confirm title={confirm.title} onCancel={() => setConfirm(null)} onConfirm={async (reason) => { await confirm.run(reason); setConfirm(null); refresh(); }} />}</div></section></main>;
}

function Panel({ section, confirm }: { section: Section; confirm: React.Dispatch<React.SetStateAction<{ title: string; run: (reason: string) => Promise<void> } | null>> }) { if (section === "overview") return <Overview />; if (section === "users") return <Users confirm={confirm} />; if (section === "moderation") return <Moderation confirm={confirm} />; if (section === "disputes") return <Disputes confirm={confirm} />; if (section === "audit") return <Audit />; return <Controls confirm={confirm} />; }
function useData<T>(path: string, deps: string[] = []) { const [data, setData] = useState<T | null>(null); const [error, setError] = useState(""); const load = useCallback(() => { setData(null); request<T>(path).then(setData).catch((e) => setError(e.message)); }, [path]); useEffect(() => { load(); const f = () => load(); window.addEventListener("admin-refresh", f); return () => window.removeEventListener("admin-refresh", f); }, [load, ...deps]); return { data, error }; }
function TableState({ error, empty = "No records found." }: { error: string; empty?: string }) { if (error) return <p className="state error">{error}</p>; return <p className="state">{empty}</p>; }
function Overview() { const { data, error } = useData<any>("/metrics"); if (!data) return <TableState error={error} empty="Loading metrics…" />; return <><div className="metric-grid">{[["Total users", data.totalUsers.toLocaleString()], ["Active jobs", data.activeJobs.toLocaleString()], ["Open disputes", data.openDisputes], ["Flagged listings", data.flaggedListings], ["Revenue · current period", `$${data.revenue.toLocaleString()}`]].map(([l, v]) => <article className="metric" key={l}><small>{l}</small><b>{v}</b></article>)}</div><div className="panel"><h2>Trust score distribution</h2><div className="chart" aria-label="Trust score distribution">{data.trustScores.map((x: any) => <div key={x.bucket} className="bar" style={{ height: `${x.value}%` }}><b>{x.value}%</b><small>{x.bucket}</small></div>)}</div></div></>; }
function Users({ confirm }: { confirm: React.Dispatch<React.SetStateAction<any>> }) { const [search, setSearch] = useState(""); const [role, setRole] = useState(""); const [status, setStatus] = useState(""); const [joinedAfter, setJoinedAfter] = useState(""); const path = `/users?page=1&pageSize=20&search=${encodeURIComponent(search)}&role=${role}&status=${status}&joinedAfter=${joinedAfter}`; const { data, error } = useData<Page<any>>(path, [search, role, status, joinedAfter]); const view = async (u: any) => { const full = await request<any>(`/users/${u.id}`); alert(`Profile: ${full.name}\nActive jobs: ${full.activeJobs}\nDisputes: ${full.disputes}`); }; return <div className="panel"><h2>Users <small>server-paginated · {data?.total ?? "…"} total</small></h2><div className="filters"><input aria-label="Search users" placeholder="Search name or email" value={search} onChange={(e) => setSearch(e.target.value)} /><select aria-label="Filter by role" value={role} onChange={(e) => setRole(e.target.value)}><option value="">All roles</option><option value="freelancer">Freelancers</option><option value="client">Clients</option></select><select aria-label="Filter by status" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option><option value="active">Active</option><option value="suspended">Suspended</option><option value="banned">Banned</option></select><input aria-label="Joined after" type="date" value={joinedAfter} onChange={(e) => setJoinedAfter(e.target.value)} /></div>{data ? <Table headers={["User", "Role", "Status", "Joined", "Actions"]}>{data.items.map((u) => <tr key={u.id}><td><b>{u.name}</b><small>{u.email}</small></td><td>{u.role}</td><td><Status value={u.status} /></td><td>{u.joinedAt}</td><td><button onClick={() => view(u)}>Profile</button><button onClick={() => confirm({ title: `${u.status === "active" ? "Suspend" : "Reinstate"} ${u.name}?`, run: async (reason: string) => request(`/users/${u.id}`, { method: "PATCH", body: JSON.stringify({ status: u.status === "active" ? "suspended" : "active", reason }) }) })}>{u.status === "active" ? "Suspend" : "Reinstate"}</button><button onClick={() => confirm({ title: `Permanently ban ${u.name}?`, run: async (reason: string) => request(`/users/${u.id}`, { method: "PATCH", body: JSON.stringify({ status: "banned", reason }) }) })}>Ban</button></td></tr>)}</Table> : <TableState error={error} empty="Loading users…" />}</div>; }
function Moderation({ confirm }: { confirm: React.Dispatch<React.SetStateAction<any>> }) { const { data, error } = useData<Page<any>>("/moderation?page=1&pageSize=20"); return <div className="panel"><h2>Listing moderation queue</h2>{data ? <Table headers={["Listing", "Owner", "Reason", "Priority", "Actions"]}>{data.items.map((j) => <tr key={j.id}><td>{j.title}</td><td>{j.owner}</td><td>{j.reason}</td><td><Status value={j.priority} /></td><td><button onClick={() => confirm({ title: "Approve this listing?", run: async (reason: string) => request(`/moderation/${j.id}`, { method: "PATCH", body: JSON.stringify({ decision: "approved", reason }) }) })}>Approve</button><button onClick={() => confirm({ title: "Reject this listing? The owner will be notified.", run: async (reason: string) => request(`/moderation/${j.id}`, { method: "PATCH", body: JSON.stringify({ decision: "rejected", reason }) }) })}>Reject</button><button onClick={() => confirm({ title: "Escalate to a senior admin?", run: async (reason: string) => request(`/moderation/${j.id}`, { method: "PATCH", body: JSON.stringify({ decision: "escalated", reason }) }) })}>Escalate</button></td></tr>)}</Table> : <TableState error={error} empty="Loading moderation queue…" />}</div>; }
function Disputes({ confirm }: { confirm: React.Dispatch<React.SetStateAction<any>> }) { const { data, error } = useData<Page<any>>("/disputes?page=1&pageSize=20"); const view = async (d: any) => { const full = await request<any>(`/disputes/${d.id}`); alert(`Thread: ${full.subject}\nParties: ${full.parties}\nTransaction: $${full.amount}`); }; return <div className="panel"><h2>Dispute resolution queue</h2>{data ? <Table headers={["ID", "Subject", "Parties", "Status", "Amount", "Actions"]}>{data.items.map((d) => <tr key={d.id}><td>{d.id}</td><td>{d.subject}</td><td>{d.parties}</td><td><Status value={d.status} /></td><td>${d.amount.toLocaleString()}</td><td><button onClick={() => view(d)}>View thread</button><button onClick={() => confirm({ title: "Resolve dispute in favour of the client?", run: async (reason: string) => request(`/disputes/${d.id}`, { method: "PATCH", body: JSON.stringify({ decision: "resolved", reason }) }) })}>Rule</button><button onClick={() => confirm({ title: "Escalate this dispute?", run: async (reason: string) => request(`/disputes/${d.id}`, { method: "PATCH", body: JSON.stringify({ decision: "escalated", reason }) }) })}>Escalate</button></td></tr>)}</Table> : <TableState error={error} empty="Loading disputes…" />}</div>; }
function Audit() { const [adminId, setAdminId] = useState(""); const [action, setAction] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const { data, error } = useData<Page<any>>(`/audit?page=1&pageSize=20&adminId=${adminId}&action=${action}&from=${from}&to=${to}`, [adminId, action, from, to]); return <div className="panel"><h2>Append-only audit log <small>7-year retention</small></h2><div className="filters"><input aria-label="Filter by admin" placeholder="Admin ID" value={adminId} onChange={(e) => setAdminId(e.target.value)} /><input aria-label="Filter by action type" placeholder="Action" value={action} onChange={(e) => setAction(e.target.value)} /><input aria-label="Start date" type="date" value={from} onChange={(e) => setFrom(e.target.value)} /><input aria-label="End date" type="date" value={to} onChange={(e) => setTo(e.target.value)} /></div>{data ? <Table headers={["Admin", "Action", "Target", "Reason", "Timestamp"]}>{data.items.map((e) => <tr key={e.id}><td>{e.adminId}</td><td>{e.action}</td><td>{e.target}</td><td>{e.reason || "—"}</td><td>{new Date(e.timestamp).toLocaleString()}</td></tr>)}</Table> : <TableState error={error} empty="Loading audit log…" />}</div>; }
function Controls({ confirm }: { confirm: React.Dispatch<React.SetStateAction<any>> }) { const { data, error } = useData<Record<string, boolean>>("/controls"); return <div className="panel narrow"><h2>Platform controls</h2><p>Every change is server-authorized and written to the append-only audit log.</p>{data ? Object.entries(data).map(([name, enabled]) => <div className="control" key={name}><span><b>{name === "jobs" ? "New job postings" : "New user registrations"}</b><small>{enabled ? "Currently enabled" : "Currently disabled"}</small></span><button className={enabled ? "toggle on" : "toggle"} aria-pressed={enabled} onClick={() => confirm({ title: `${enabled ? "Disable" : "Enable"} ${name}?`, run: async () => request(`/controls/${name}`, { method: "PATCH", body: JSON.stringify({ enabled: !enabled }) }) })}>{enabled ? "On" : "Off"}</button></div>) : <TableState error={error} empty="Loading controls…" />}</div>; }
function Table({ headers, children }: { headers: string[]; children: React.ReactNode }) { return <div className="table-wrap"><table><thead><tr>{headers.map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }
