/**
 * MapKeys and MapValues utilities.
 * Creates an object with mapped keys or mapped values.
 */

/**
 * Creates an object with the same values as object and keys generated by iteratee.
 * Prototype pollution safe.
 * @param {Object} object The object to iterate over.
 * @param {Function} [iteratee] The function invoked per iteration.
 * @returns {Object} Returns the new mapped object.
 */
export function mapKeys(object, iteratee) {
    const result = Object.create(null);
    if (object == null || typeof object !== "object") {
        return {};
    }

    const fn = typeof iteratee === "function" ? iteratee : (val, key) => key;
    const keys = Object.keys(object);

    for (const key of keys) {
        const newKey = String(fn(object[key], key, object));
        if (newKey === "__proto__" || newKey === "constructor" || newKey === "prototype") {
            continue;
        }
        result[newKey] = object[key];
    }

    return Object.assign({}, result);
}

/**
 * Creates an object with the same keys as object and values generated by iteratee.
 * @param {Object} object The object to iterate over.
 * @param {Function|string} [iteratee] The function invoked per iteration.
 * @returns {Object} Returns the new mapped object.
 */
export function mapValues(object, iteratee) {
    const result = {};
    if (object == null || typeof object !== "object") {
        return {};
    }

    const fn = typeof iteratee === "function"
        ? iteratee
        : typeof iteratee === "string"
        ? (val) => (val != null ? val[iteratee] : undefined)
        : (val) => val;

    const keys = Object.keys(object);
    for (const key of keys) {
        result[key] = fn(object[key], key, object);
    }

    return result;
}