import { asyncHandler } from '../../utils/asyncHandler.js';

// ... existing controller code ...

export const sendMessage = asyncHandler(async (req, res) => {
  // ... existing implementation ...
});

export const getMessages = asyncHandler(async (req, res) => {
  // ... existing implementation ...
});

// ... other message controller methods ...