import { asyncHandler } from '../../utils/asyncHandler.js';

// ... existing controller code ...

export const createNotification = asyncHandler(async (req, res) => {
  // ... existing implementation ...
});

export const getNotifications = asyncHandler(async (req, res) => {
  // ... existing implementation ...
});

// ... other notification controller methods ...