import { asyncHandler } from '../../utils/asyncHandler.js';

// ... existing controller code ...

export const createPayment = asyncHandler(async (req, res) => {
  // ... existing implementation ...
});

export const getPayment = asyncHandler(async (req, res) => {
  // ... existing implementation ...
});

// ... other payment controller methods ...