import { asyncHandler } from '../../utils/asyncHandler.js';

// ... existing controller code ...

export const createProposal = asyncHandler(async (req, res) => {
  // ... existing implementation ...
});

export const getProposals = asyncHandler(async (req, res) => {
  // ... existing implementation ...
});

// ... other proposal controller methods ...