import { asyncHandler } from '../../utils/asyncHandler.js';

// ... existing controller code ...

export const createUser = asyncHandler(async (req, res) => {
  // ... existing implementation ...
});

export const getUser = asyncHandler(async (req, res) => {
  // ... existing implementation ...
});

// ... other user controller methods ...