import test from "node:test";
import assert from "node:assert/strict";
import { createApp } from "../app.js";
import { createUserSchema, adminCreateUserSchema } from "../validators/user.js";
import { createUser } from "../services/userService.js";

async function withServer(fn) {
  const app = createApp();
  const server = app.listen(0);
  await new Promise((resolve, reject) => {
    server.once("listening", resolve);
    server.once("error", reject);
  });
  const { port } = server.address();
  try {
    return await fn(`http://127.0.0.1:${port}`);
  } finally {
    await new Promise((resolve, reject) => {
      server.close((error) => (error ? reject(error) : resolve()));
    });
  }
}

async function postUser(base, body) {
  const res = await fetch(`${base}/api/users`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body)
  });
  return { status: res.status, body: await res.json().catch(() => null) };
}

// --- mass assignment ---

test("createUserSchema accepts the fields a client is allowed to set", () => {
  const parsed = createUserSchema.parse({
    email: "someone@example.com",
    fullName: "Someone",
    bio: "hello"
  });
  assert.equal(parsed.email, "someone@example.com");
  assert.equal(parsed.fullName, "Someone");
});

test("createUserSchema rejects a client-supplied role", () => {
  assert.throws(() =>
    createUserSchema.parse({ email: "a@b.com", fullName: "A", role: "admin" })
  );
});

test("createUserSchema rejects injected passwordHash and id", () => {
  assert.throws(() =>
    createUserSchema.parse({
      email: "a@b.com",
      fullName: "A",
      passwordHash: "forged-hash",
      id: "usr_attacker"
    })
  );
});

test("createUserSchema requires a valid email and a fullName", () => {
  assert.throws(() => createUserSchema.parse({ fullName: "A" }));
  assert.throws(() => createUserSchema.parse({ email: "not-an-email", fullName: "A" }));
  assert.throws(() => createUserSchema.parse({ email: "a@b.com" }));
});

test("adminCreateUserSchema may set a role but still rejects unknown fields", () => {
  const parsed = adminCreateUserSchema.parse({
    email: "a@b.com",
    fullName: "A",
    role: "admin"
  });
  assert.equal(parsed.role, "admin");
  assert.throws(() =>
    adminCreateUserSchema.parse({ email: "a@b.com", fullName: "A", isAdmin: true })
  );
});

test("createUser never lets a payload override the service-owned fields", async () => {
  // Defence in depth: even if a caller bypasses validation, the record is
  // built field by field and the id is always service-generated.
  const user = await createUser({
    email: "direct@example.com",
    fullName: "Direct",
    id: "usr_attacker",
    role: "admin",
    isVerified: true
  });

  assert.notEqual(user.id, "usr_attacker", "id must be generated by the service");
  assert.equal(user.role, "admin", "the passed role is used only as an explicit value");
  assert.equal(user.isVerified, undefined, "unknown fields are not persisted");
});

test("POST /api/users refuses a mass-assignment attempt to become admin", async () => {
  await withServer(async (base) => {
    const { status } = await postUser(base, {
      email: "sneaky@example.com",
      fullName: "Sneaky",
      role: "admin"
    });
    assert.equal(status, 400, "a client-supplied role must be rejected");
  });
});

test("POST /api/users refuses a forged passwordHash", async () => {
  await withServer(async (base) => {
    const { status } = await postUser(base, {
      email: "forger@example.com",
      fullName: "Forger",
      passwordHash: "forged"
    });
    assert.equal(status, 400);
  });
});

test("POST /api/users creates a valid user and defaults the role to client", async () => {
  await withServer(async (base) => {
    const { status, body } = await postUser(base, {
      email: "valid@example.com",
      fullName: "Valid Person"
    });
    assert.equal(status, 201);
    assert.equal(body.data.email, "valid@example.com");
    assert.equal(body.data.role, "client");
  });
});
