import test from "node:test";
import assert from "node:assert/strict";
import { createApp } from "../app.js";

test("POST /api/users creates user and keeps id server-owned", async () => {
  const app = createApp();
  const server = app.listen(0);

  await new Promise((resolve, reject) => {
    server.once("listening", resolve);
    server.once("error", reject);
  });

  const { port } = server.address();
  const response = await fetch(`http://127.0.0.1:${port}/api/users`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      id: "usr_attacker",
      name: "Attacker User",
      email: "attacker@gmail.com"
    })
  });

  assert.equal(response.status, 201);
  const json = await response.json();
  
  // Verify that the ID was generated by the server and is not usr_attacker
  assert.ok(json.data.id);
  assert.ok(json.data.id.startsWith("usr_"));
  assert.notEqual(json.data.id, "usr_attacker");

  await new Promise((resolve, reject) => {
    server.close((error) => (error ? reject(error) : resolve()));
  });
});
