#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
from math import isqrt
from pathlib import Path


DIGITS = 500_000
GUARD_DIGITS = 20
TERMS_PER_DIGIT = 14.181647462725477
ISSUE_SEED_100 = (
    "141592653589793238462643383279502884197169399375105820974944592307816406"
    "2862089986280348253421170679"
)
DEFAULT_OUTPUT = Path("docs/pi/pi-500000.md")


def binary_split(a: int, b: int) -> tuple[int, int, int]:
    """Return P, Q, T terms for the Chudnovsky binary-splitting series."""
    if b - a == 1:
        if a == 0:
            return 1, 1, 13_591_409

        p = (6 * a - 5) * (2 * a - 1) * (6 * a - 1)
        q = a * a * a * 10_939_058_860_032_000
        t = p * (13_591_409 + 545_140_134 * a)

        if a % 2:
            t = -t

        return p, q, t

    midpoint = (a + b) // 2
    p_left, q_left, t_left = binary_split(a, midpoint)
    p_right, q_right, t_right = binary_split(midpoint, b)

    return (
        p_left * p_right,
        q_left * q_right,
        q_right * t_left + p_left * t_right,
    )


def pi_digits(digits: int) -> str:
    terms = int(digits / TERMS_PER_DIGIT) + 2
    scale_digits = digits + GUARD_DIGITS
    scale = 10**scale_digits

    p, q, t = binary_split(0, terms)
    del p

    sqrt_10005 = isqrt(10_005 * scale * scale)
    pi_scaled = (q * 426_880 * sqrt_10005) // t
    compact = str(pi_scaled)

    expected_len = scale_digits + 1
    if len(compact) < expected_len:
        compact = compact.zfill(expected_len)

    return f"{compact[0]}.{compact[1:digits + 1]}"


def grouped_digits(compact: str) -> str:
    digits = compact.split(".", 1)[1]
    groups = [digits[index : index + 10] for index in range(0, len(digits), 10)]
    lines = [" ".join(groups[index : index + 10]) for index in range(0, len(groups), 10)]
    return "3.\n" + "\n".join(lines)


def build_document(compact: str) -> str:
    fractional = compact.split(".", 1)[1]
    digest = hashlib.sha256(compact.encode("ascii")).hexdigest()
    grouped = grouped_digits(compact)

    return f"""# PI to 500,000 Decimal Places

This artifact continues issue #2885 with a reproducible 500,000-decimal-place
prefix of PI. The value is generated by `scripts/generate_pi_500000.py` using
the Chudnovsky series with integer binary splitting and Python standard-library
arithmetic only.

- Decimal places after the point: {len(fractional)}
- SHA-256 of compact `3.<digits>` value: `{digest}`
- First 100 decimals match the issue seed: `{fractional[:100] == ISSUE_SEED_100}`
- Verification command: `python3 scripts/generate_pi_500000.py --check`

<!-- BEGIN_PI_500000 -->
```text
{grouped}
```
<!-- END_PI_500000 -->
"""


def parse_document(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    start = text.index("```text\n") + len("```text\n")
    end = text.index("\n```", start)
    return text[start:end].replace("\n", "").replace(" ", "")


def validate(compact: str, digits: int) -> str:
    if not compact.startswith("3."):
        raise AssertionError("PI value must start with 3.")

    fractional = compact.split(".", 1)[1]
    if len(fractional) != digits:
        raise AssertionError(f"Expected {digits} decimals, found {len(fractional)}.")

    if fractional[:100] != ISSUE_SEED_100:
        raise AssertionError("First 100 decimals do not match the issue seed.")

    return hashlib.sha256(compact.encode("ascii")).hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate and verify PI to 500,000 decimals.")
    parser.add_argument("--digits", type=int, default=DIGITS)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="Verify the committed artifact.")
    args = parser.parse_args()

    if args.check:
        compact = parse_document(args.output)
    else:
        compact = pi_digits(args.digits)
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(build_document(compact), encoding="utf-8")

    digest = validate(compact, args.digits)
    print(f"digits={args.digits}")
    print(f"sha256={digest}")
    print(f"first100={compact.split('.', 1)[1][:100]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
