#!/usr/bin/env python3
"""Generate and verify a 150,000-decimal PI artifact for issue #2883."""

from __future__ import annotations

import argparse
import hashlib
import math
import sys
from pathlib import Path


if hasattr(sys, "set_int_max_str_digits"):
    sys.set_int_max_str_digits(0)


DECIMALS = 150_000
ISSUE_SEED = "3.1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679"
CHUDNOVSKY_C = 640_320
CHUDNOVSKY_C3_OVER_24 = CHUDNOVSKY_C**3 // 24


def binary_split(a: int, b: int) -> tuple[int, int, int]:
    if b - a == 1:
        if a == 0:
            return 1, 1, 13_591_409

        p = (6 * a - 5) * (2 * a - 1) * (6 * a - 1)
        q = a * a * a * CHUDNOVSKY_C3_OVER_24
        t = p * (13_591_409 + 545_140_134 * a)
        if a % 2:
            t = -t
        return p, q, t

    mid = (a + b) // 2
    p_left, q_left, t_left = binary_split(a, mid)
    p_right, q_right, t_right = binary_split(mid, b)

    p = p_left * p_right
    q = q_left * q_right
    t = q_right * t_left + p_left * t_right
    return p, q, t


def pi_compact(decimal_places: int) -> str:
    guard_digits = 20
    scale_digits = decimal_places + guard_digits
    terms = math.ceil(scale_digits / 14.181647462725477) + 1

    _, q, t = binary_split(0, terms)
    one = 10**scale_digits
    sqrt_10005 = math.isqrt(10_005 * one * one)
    scaled_pi = (q * 426_880 * sqrt_10005) // t

    value = str(scaled_pi)
    compact = f"{value[0]}.{value[1:decimal_places + 1]}"
    if len(compact.split(".", 1)[1]) != decimal_places:
        raise RuntimeError("generated PI value has an unexpected length")
    if not compact.startswith(ISSUE_SEED):
        raise RuntimeError("generated PI value does not match the discussion seed")
    return compact


def grouped_decimal(decimal_digits: str) -> str:
    groups = [decimal_digits[index : index + 10] for index in range(0, len(decimal_digits), 10)]
    lines = []
    for index in range(0, len(groups), 10):
        lines.append(" ".join(groups[index : index + 10]))
    return "\n".join(lines)


def artifact_text(compact: str) -> str:
    digest = hashlib.sha256(compact.encode("ascii")).hexdigest()
    decimals = compact.split(".", 1)[1]
    grouped = grouped_decimal(decimals)

    return f"""# PI to 150,000 Decimal Places for Issue #2883

This artifact continues discussion #2872 for issue #2883 with a reproducible
150,000-decimal-place prefix of PI. The value is generated by
`scripts/generate_pi_150000_2883.py` using the Chudnovsky series, binary
splitting, and Python standard-library integer arithmetic.

- Decimal places after the point: 150000
- SHA-256 of the compact `3.<digits>` value: `{digest}`
- Verification command: `python scripts/generate_pi_150000_2883.py --check`
- Discussion seed check: first 100 decimal places match discussion #2872

<!-- BEGIN_PI_150000_2883 -->
```text
3.
{grouped}
```
<!-- END_PI_150000_2883 -->
"""


def read_compact_from_artifact(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    start_marker = "<!-- BEGIN_PI_150000_2883 -->"
    end_marker = "<!-- END_PI_150000_2883 -->"
    start = text.index(start_marker)
    end = text.index(end_marker, start)
    block = text[start:end].split("```text", 1)[1].split("```", 1)[0]
    digits = "".join(character for character in block if character.isdigit())
    if not digits.startswith("3"):
        raise RuntimeError("artifact does not contain a compact PI value")
    return f"{digits[0]}.{digits[1:]}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify the existing artifact instead of rewriting it")
    parser.add_argument(
        "--output",
        default="docs/pi/pi-150000-2883.md",
        type=Path,
        help="artifact path to write or verify",
    )
    args = parser.parse_args()

    compact = pi_compact(DECIMALS)
    expected_text = artifact_text(compact)

    if args.check:
        existing = args.output.read_text(encoding="utf-8")
        existing_compact = read_compact_from_artifact(args.output)
        if existing != expected_text:
            raise RuntimeError("artifact content differs from regenerated output")
        if existing_compact != compact:
            raise RuntimeError("artifact PI digits differ from regenerated output")
        print(f"verified {args.output} with {DECIMALS} decimal places")
        print(f"sha256={hashlib.sha256(compact.encode('ascii')).hexdigest()}")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(expected_text, encoding="utf-8")
    print(f"wrote {args.output} with {DECIMALS} decimal places")
    print(f"sha256={hashlib.sha256(compact.encode('ascii')).hexdigest()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
