"""Generate and verify a 20,000-decimal-place PI artifact.

This uses the Chudnovsky series with integer binary splitting and only the
Python standard library. Running the script rewrites PI_20000.md and verifies
that the embedded SHA-256 matches the compact decimal string.
"""

from __future__ import annotations

import hashlib
import math
import sys
from pathlib import Path

if hasattr(sys, "set_int_max_str_digits"):
    sys.set_int_max_str_digits(0)

DIGITS = 20_000
EXTRA_DIGITS = 10
TERMS = DIGITS // 14 + 2
CHUDNOVSKY_C = 640_320
CHUDNOVSKY_C3_OVER_24 = CHUDNOVSKY_C**3 // 24
OUT = Path(__file__).resolve().parents[1] / "PI_20000.md"


def binary_split(a: int, b: int) -> tuple[int, int, int]:
    if b - a == 1:
        if a == 0:
            return 1, 1, 13_591_409

        p = (6 * a - 5) * (2 * a - 1) * (6 * a - 1)
        q = a**3 * CHUDNOVSKY_C3_OVER_24
        t = p * (13_591_409 + 545_140_134 * a)
        if a % 2:
            t = -t
        return p, q, t

    mid = (a + b) // 2
    p1, q1, t1 = binary_split(a, mid)
    p2, q2, t2 = binary_split(mid, b)
    return p1 * p2, q1 * q2, t1 * q2 + p1 * t2


def compute_pi(digits: int) -> str:
    scale = 10 ** (digits + EXTRA_DIGITS)
    _, q, t = binary_split(0, TERMS)
    sqrt_10005 = math.isqrt(10_005 * scale * scale)
    pi_scaled = (q * 426_880 * sqrt_10005) // t
    value = str(pi_scaled // (10**EXTRA_DIGITS))
    return f"{value[0]}.{value[1:]}"


def wrap_digits(value: str, width: int = 100) -> str:
    head, tail = value.split(".")
    lines = [head + "."]
    lines.extend(tail[i : i + width] for i in range(0, len(tail), width))
    return "\n".join(lines)


def artifact(value: str) -> str:
    compact_hash = hashlib.sha256(value.encode("ascii")).hexdigest()
    continuation = value.split(".", 1)[1][5000:]
    continuation_hash = hashlib.sha256(continuation.encode("ascii")).hexdigest()
    return f"""# PI to 20,000 Decimal Places

This artifact extends the reproducible PI trail for issue #2883 beyond the
existing 5,000-decimal-place submission. The decimal string below contains
exactly 20,000 digits after the decimal point and is generated by
`scripts/verify_pi_20000.py` using the Chudnovsky series with integer binary
splitting.

## Verification

- Generator/verifier: `python scripts/verify_pi_20000.py`
- Decimal places after point: `{len(value.split('.', 1)[1])}`
- SHA-256 of compact `3.<digits>` string: `{compact_hash}`
- SHA-256 of continuation digits 5001-20000: `{continuation_hash}`
- No third-party dependencies are required.

## Value

```text
{wrap_digits(value)}
```
"""


def main() -> None:
    value = compute_pi(DIGITS)
    decimals = value.split(".", 1)[1]
    if len(decimals) != DIGITS:
        raise SystemExit(f"expected {DIGITS} decimals, got {len(decimals)}")

    OUT.write_text(artifact(value), encoding="utf-8", newline="\n")

    rendered = OUT.read_text(encoding="utf-8")
    expected_hash = hashlib.sha256(value.encode("ascii")).hexdigest()
    if expected_hash not in rendered:
        raise SystemExit("artifact hash verification failed")

    print(f"wrote {OUT.name} with {DIGITS} decimal places")
    print(f"sha256={expected_hash}")


if __name__ == "__main__":
    main()
