/**
 * Central error handling middleware for the API.
 *
 * This middleware normalises errors coming from the application and ensures that
 * the HTTP status code and response payload follow the API contract.
 *
 * Special handling is added for JSON parsing errors generated by `express.json()`
 * when the request declares an unsupported charset or uses an unsupported
 * content‑encoding. In those cases we must return **415 Unsupported Media Type**
 * with a structured error envelope.
 *
 * All other errors default to the existing behaviour:
 *   - If the error already contains a valid HTTP status (4xx/5xx) we honour it.
 *   - Otherwise we treat it as an unexpected server error and respond with 500.
 *
 * The response envelope follows the API convention:
 *   { message: "<human readable description>" }
 */

function errorHandler(err, _req, res, _next) {
  // ------------------------------------------------------------
  // 1️⃣  Unsupported JSON charset / encoding errors from express.json()
  // ------------------------------------------------------------
  // express.json() throws an error object with a `type` property.
  //   * "charset.unsupported" – the request declared a charset that JSON does not support.
  //   * "encoding.unsupported" – the request used a Content‑Encoding that cannot be decoded.
  // For both cases the API contract requires a 415 response with a generic
  // "Unsupported media type" message.
  if (err && (err.type === 'charset.unsupported' || err.type === 'encoding.unsupported')) {
    return res.status(415).json({ message: 'Unsupported media type' });
  }

  // ------------------------------------------------------------
  // 2️⃣  Preserve explicit client‑error status codes (4xx) when they exist.
  // ------------------------------------------------------------
  const explicitStatus = typeof err?.status === 'number' ? err.status : null;
  const isClientError = explicitStatus && explicitStatus >= 400 && explicitStatus < 500;
  const isServerError = explicitStatus && explicitStatus >= 500 && explicitStatus < 600;

  // If the error already carries a proper HTTP status, honour it.
  if (isClientError || isServerError) {
    const message = err.message || (isServerError ? 'Unexpected server error' : 'Bad request');
    return res.status(explicitStatus).json({ message });
  }

  // ------------------------------------------------------------
  // 3️⃣  Fallback – unexpected errors → 500
  // ------------------------------------------------------------
  console.error(err); // retain logging for debugging
  return res.status(500).json({ message: 'Unexpected server error' });
}

module.exports = errorHandler;
